### ISSUE TITLE
Running Commands on Remote Development Host Fails

### ISSUE THREAD

**Issue by remiscarlet** [doki-theme/doki-theme-vscode#168] opened 2022-08-03 18:58 UTC
**Describe the bug**
Running Doki theme installation/sticker&bg removal commands fail when working via remote development.

I'm fairly new to VSCode but it seems that Doki must be installed on both local and remote hosts for the theming to work properly - Themed CSS appear to not load when Doki Theme is not installed on the remote host.

A workaround is to simply run the commands on a non-remote window then command palette -> `Reload Window`

**To Reproduce**
1. Install fresh VSCode for Mac and the Remote-SSH (v0.84.0) extension
2. Set up SSH host and connect
3. Install Doki-Theme (v84.1.6) on both local and remote hosts
4. Command Palette -> `>Doki-Theme: Install Vanilla's Sticker` (etc)
5. Follow the `sudo chmod` instructions in the `Asset Installation Help` (etc) window
6. Repeat `>Doki-Theme: Install Vanilla's Sticker` (etc)
 
**Expected Behavior**
- Running the same command after following the chmod instructions should work.
- Should be able to run these commands in the remotely connected window.

**Environment**
Version: 1.69.2 (Universal)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z (2 wks ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.4.0

Doki-Theme (v84.1.6) 

**Logs**
This seems to be the only log with a stacktrace, but I can provide other logs if needed.
[window.log](https://github.com/doki-theme/doki-theme-vscode/files/9254258/window.log)

**Note**
Perhaps related to https://github.com/doki-theme/doki-theme-vscode/issues/164

**Comment by Unthrottled** [comment] 2022-08-03 21:24
Hmm, that sounds similar to this comment?

https://github.com/doki-theme/doki-theme-vscode/issues/131#issuecomment-1066969847

If it is, where does yours normally fail? Because last I tried the assets get carried over in the new VS Code that gets brought up.

**Comment by remiscarlet** [comment] 2022-08-03 22:26
Reading through the comment, I'm not entirely sure if it's the same issue. For me, the themes (once installed locally) will show up correctly in both local and remote environments. The issue is mainly that I'm unable to run commands to install/remove themes while on a remotely connected window. 

Not sure if this recording is helpful but in it I demonstrate attempting to add stickers/bgs in a remote window and it failing, even after changing ownership of files as per the helper tabs. I then do the same commands on a local window which succeeds. Reloading both windows will successfully display the sticker/bg. I repeat the same for the removal commands.

Interestingly, the sticker still shows up in the help info tab when the command fails on the remote window, even though it should be uninstalled.

![output](https://user-images.githubusercontent.com/2812190/182723022-033a53b3-f1f6-4fa7-aff8-07cfa8221c27.gif)

**Comment by Unthrottled** [comment] 2022-08-03 22:38
> The issue is mainly that I'm unable to run commands to install/remove themes while on a remotely connected window.

Ah that's because the your vscode running on your MacBook is acting as a client (front-end) to your remote session. Which explains why the removal on your non connected works for both of your VSCode windows. 

The issue is that when you are connected to your remote session, the guts (backend) of vscode are provided by the remote code server. So when you run the command there, it's  different environment. 

I think you just need to run the command once on your non-connected VS code instance, and it will carry over (based on the gif you uploaded, which was handy, thanks!). 

That should fix your issue, correct?

> As an aside, I don't usually upload recordings to github but is there an easy way to upload files larger than 10mb? Had to compress the recording to a gif (no scrubbing) due to filesize limits

I'm on a MacBook, so I normally just do the screen recording then just use [ffmpeg](https://ffmpeg.org/) to convert to mp4, ex

```shell
ffmpeg -i Screen\ Recording\ 2022-07-13\ at\ 3.00.31\ PM.mov -vcodec h264 -acodec mp2 animation.mp4
```

you can also adjust the sizing during conversion as well to make it smaller, but typically the mp4 is smaller

**Comment by remiscarlet** [comment] 2022-08-03 23:28
If the behavior of needing to run the commands on a local environment is intended, then I'd say that's okay! (As opposed to somehow being able to pass those commands back to a local env context)

However, if that's the case I think for usability purposes it might be nice if the helper tab that gets opened up can either detect it's in a remote environment and show an appropriately tailored helper tab, or to include said information in the current set of helper tabs. (Something like "Hey, I think you're trying to run me in a remote context which won't work! Please try again in a local context." etc)

Either way, I appreciate the helpful info and context! And thank you for the ffmpeg tip as well! I always forget how powerful ffmpeg is 😅 


Finally, would it be better for this issue to be closed and to reopen with a feature request for the above or just keep it as is?

**Comment by Unthrottled** [comment] 2022-08-03 23:36
> However, if that's the case I think for usability purposes it might be nice if the helper tab that gets opened up can either detect it's in a remote environment and show an appropriately tailored helper tab, or to include said information in the current set of helper tabs. (Something like "Hey, I think you're trying to run me in a remote context which won't work! Please try again in a local context." etc)

I'll include something that calls out the `SSH` connection explicitly. This plugin _should_ work if running on a code server, but I don't think the `SSH` connection is the same (I can investigate more when I work #164 ). 

So you can leave this open, I'll close it when I've added this to the help menu. 

Thanks for providing helpful debugging information!

**Closed** 2022-08-08 10:49 UTC
