### ISSUE TITLE
User not notified if unable to auto-fix checksum

### ISSUE THREAD

**Issue by alxgnon** [doki-theme/doki-theme-vscode#136] opened 2022-03-23 19:56 UTC
**Describe the bug**

I saw that there was a pull request that purported to fix the [Unsupported] warning by recalculating the checksum after assets were installed. However, I was not able to get this to work.

**To Reproduce**

1. Install any sticker or background asset.
2. Restart VSCode.

**Expected Behavior**

No annoying [Unsupported] Warning.

**Environment**

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.16-arch1-1

Doki Theme version: v74.1.1

**Screenshots**

![Screenshot_2022-03-23_15-42-46](https://user-images.githubusercontent.com/4480082/159784414-1c10fc7d-f4b2-4abc-a6c6-e1469490867f.png)

**Comment by Unthrottled** [comment] 2022-03-23 20:57
Are you completely closing all of vscode and not just reloading the window?

![Peek 2022-03-23 15-52](https://user-images.githubusercontent.com/15972415/159794276-e76c10b5-0176-4eb6-b336-e625b44088da.gif)


I am unable to reproduce the issue, my env:

```
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-104-generic
```

**Comment by alxgnon** [comment] 2022-03-23 21:03
Yes, I have been restarting vscode and I get this problem. I've noticed that when restarting, the [Unsupported] message only appears after 2 to 3 seconds.

**Comment by Unthrottled** [comment] 2022-03-23 22:12
:thinking: 

Okay, the only other thing that I can think of is that the `products.json` file is not writeable.

On my machine the file is `/usr/share/code/resources/app/product.json`. Could you make sure that whatever process is running VSCode has the ability to change files `/usr/share/code/resources/app/` (or wherever your vscode is installed)

If that doesn't work (making that file writable), there is some logging, so I'll ask you to provide logs after running a asset installation command.

**Comment by alxgnon** [comment] 2022-03-23 23:27
For me, the product.json file is found at `/opt/visual-studio-code/resources/app/product.json`. I checked the logs and it was in fact a permissions issue.

I gave permissions to create files in the `/opt/visual-studio-code/resources/app/` folder, as well as the permission to modify the product.json file, and now it works!!

Finally, I think that it would be useful to have some way to inform the user how to fix that problem if it occurs. Myself, I installed VSCode through the `visual-studio-code-bin` package in the AUR, so I assume anyone else who did the same would encounter that problem, as well as anyone who installed VSCode system-wide in a non-user writeable directory.

**Comment by Unthrottled** [comment] 2022-03-23 23:34
Hurray Fixed!

> Finally, I think that it would be useful to have some way to inform the user how to fix that problem if it occurs.

I was planning on adding that right after I discovered that may have been the issue. 
I'm working on some new themes, so I'll swing around and close this issue when that time comes.

Thank you for providing all the supporting information to help diagnosis the issue!

**Closed** 2022-04-04 14:38 UTC
Labels: bug
