### ISSUE TITLE
Wallpaper and Sticker not working

### ISSUE THREAD

**Issue by master117** [doki-theme/doki-theme-vscode#61] opened 2021-04-15 15:19 UTC
**Describe the bug**
Wallpaper and Sticker not working.

I switch VSCode to admin then download the extension, switch to Rem Theme (works). Then I add sticker and background via ctrl+shift+p menu and restart vscode. Neither Wallpaper nor Sticker show up. Extension works in IntelliJ.

**Environment**
Windows, VSCode 1.55.2, Doki Theme v11.1.1

![image](https://user-images.githubusercontent.com/444009/114894153-ae8ae100-9e0e-11eb-9792-851cda48a7a1.png)

**Comment by Unthrottled** [comment] 2021-04-15 22:31
https://user-images.githubusercontent.com/15972415/114945530-1f31fd80-9e0f-11eb-89d9-c8753d7dcf58.mp4

Just to make sure that I am on the same page. You were able to run all of the steps above (minus the checksum) and all of the notifications showed up saying it worked?


---

If that is the case then, I'll ask you to inspect the VS Code `workbench.desktop.main.css` file.

Here is where mine is, if that helps


```
C:\Users\birdm.DESKTOP-FO92PV5\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench
```

![image](https://user-images.githubusercontent.com/15972415/114945396-dd08bc00-9e0e-11eb-950d-6419c7cb48dd.png)


At the bottom of the the css file, you should see the background/sticker styles.

![image](https://user-images.githubusercontent.com/15972415/114945465-fa3d8a80-9e0e-11eb-92ab-e4e5727aecfc.png)

You'll probably want to check to see if those files exist. If not, you're free to change them to whatever you want :) 

These are the defaults downloaded by the plugin:

**Glass Pane Wallpaper**
[https://doki.assets.unthrottled.io/backgrounds/wallpapers/transparent/rem.png](https://doki.assets.unthrottled.io/backgrounds/wallpapers/transparent/rem.png)

**Empty Editor Background**
[https://doki.assets.unthrottled.io/backgrounds/wallpapers/rem.png](https://doki.assets.unthrottled.io/backgrounds/wallpapers/rem.png)

**Sticker**
[https://doki.assets.unthrottled.io/stickers/vscode/reZero/rem/rem.png](https://doki.assets.unthrottled.io/stickers/vscode/reZero/rem/rem.png)

---

I think it may be an issue of the plugin not being able to save the assets in the directory specified by the CSS file.

Let me know if that helps, you need more info, or you solved the problem.

**Comment by master117** [comment] 2021-04-16 07:04
Ok the CSS definitely got applied. 

![image](https://user-images.githubusercontent.com/444009/114984850-6c0ae800-9e92-11eb-9cc9-77a9581da279.png)

But the images are missing from the specified directory. 

![image](https://user-images.githubusercontent.com/444009/114984764-58f81800-9e92-11eb-9105-6771f1c62d04.png)

>I think it may be an issue of the plugin not being able to save the assets in the directory specified by the CSS file.

Probably, yes. What is the easiest way to get the images manually? Extract them from the .md files?

**Comment by smokeSH** [comment] 2021-04-24 20:06
Same issue for me. Did not find a fix so far.

**Comment by master117** [comment] 2021-04-24 20:31
> Same issue for me. Did not find a fix so far.

Put the Images into the folder they should be in as indicated by the css.

**Comment by Unthrottled** [comment] 2021-04-24 21:22
@smokeSH Are you also on windows 10?

**Comment by Clxmmm** [comment] 2021-04-27 07:39
I've almost the same problem expect for non-existing files.
![image](https://user-images.githubusercontent.com/42498403/116202996-8028d200-a73b-11eb-85c4-8b12c229e45d.png)
I'm on W10, my VSCode is up to date. 
Installed this extension on my two computers and same issue on them.

Any idea? Thanks

**Comment by master117** [comment] 2021-04-27 09:20
> I've almost the same problem expect for non-existing files.
> ![image](https://user-images.githubusercontent.com/42498403/116202996-8028d200-a73b-11eb-85c4-8b12c229e45d.png)
> I'm on W10, my VSCode is up to date.
> Installed this extension on my two computers and same issue on them.
> 
> Any idea? Thanks

That makes it a very different issue. See if the css files are where they are supposed to be and reload your VS.

**Comment by Unthrottled** [comment] 2021-04-27 11:15
@master117 I am trying to reproduce this issue, and I can't. Do you have this issue if you attempt to install a sticker/wallpaper of another girl?

If so, could you take a peek at the `console` [developer tools, please](https://stackoverflow.com/questions/30765782/what-is-the-use-of-the-developer-tools-in-vs-code)

![image](https://user-images.githubusercontent.com/15972415/116232373-ab9dc380-a71f-11eb-88d4-b878577ff145.png)

I have some code that doesn't attempt to download the asset if it checked already that day, and am wondering if that is being a jerk. I already have code that creates the directories if they don't exists, so it can put the assets where they need to be.

**Comment by master117** [comment] 2021-04-27 11:46
@Unthrottled Sure

![grafik](https://user-images.githubusercontent.com/444009/116235689-76649600-a75e-11eb-8f3a-391ace621f23.png)

It seems like there is some problem in that script. But I think I figured out what the problem is.

![grafik](https://user-images.githubusercontent.com/444009/116235895-aca21580-a75e-11eb-9b65-4baae46a6e3e.png)

I was able to download a new wallpaper after leaving my companies vpn. So this is most likely a proxy issue. I just didn't realize because the first time I tried that I already had tried once for that wallpaper within that day. So the optimization got me.

**Comment by Unthrottled** [comment] 2021-04-27 13:03
@master117 Great! That's what I thought it might have been, that's what I get for trying to be clever.

I'll have a fix out that will always attempt to download or update the asset when a user attempts to install a new/same asset.

Thanks for the insights and helping out the others having issues!

**Comment by master117** [comment] 2021-04-27 14:00
Maybe an error message for failed downloads would be good. I can test it if you want.

**Comment by Clxmmm** [comment] 2021-04-27 17:26
> > I've almost the same problem expect for non-existing files.
> > ![image](https://user-images.githubusercontent.com/42498403/116202996-8028d200-a73b-11eb-85c4-8b12c229e45d.png)
> > I'm on W10, my VSCode is up to date.
> > Installed this extension on my two computers and same issue on them.
> > Any idea? Thanks
> 
> That makes it a very different issue. See if the css files are where they are supposed to be and reload your VS.

Okay, just checked on my main computer. The workbench css file is in my HDD and the wallpapers are in my SSD. I really don't know if it change anything. In the css file the images are at the right place.

**Comment by Unthrottled** [comment] 2021-04-27 21:18
@Clxmmm Did you check the content's of the CSS? At the bottom of the file you should see some of relevant css.

![Example](https://user-images.githubusercontent.com/444009/114984850-6c0ae800-9e92-11eb-9cc9-77a9581da279.png)

**Comment by Clxmmm** [comment] 2021-04-27 21:22
@Unthrottled Yep, i've exactly the same css except for the bg-pos which is centered. Images redirects at right url etc...

**Comment by master117** [comment] 2021-04-27 21:25
Do you see the css getting applied in the vsc developer tools? @Clxmmm

**Comment by Clxmmm** [comment] 2021-04-27 21:30
> Do you see the css getting applied in the vsc developer tools inspector? @Clxmmm

![image](https://user-images.githubusercontent.com/42498403/116315197-78574500-a7b0-11eb-89ba-f2cbd8d36865.png)
Yep right here in first pos of styles

**Comment by Unthrottled** [comment] 2021-04-27 22:46
@Clxmmm and there is nothing in the developer tools console that says that local content is blocked?

Have you tried changing the url in the css to point at https://doki.assets.unthrottled.io/backgrounds/wallpapers/transparent/rem.png and reloading VS code?

**Comment by Clxmmm** [comment] 2021-04-27 23:03
![image](https://user-images.githubusercontent.com/42498403/116322689-d38f3480-a7bc-11eb-88c6-cb7d5408cfc6.png)
Okay so just tried with the web link it's working (see on screen)
Now checked in the devtool if css is working so I checked in the abyss of VSC CSS for finding the 
`[id="workbench.parts.editor"] .split-view-view .editor-container .editor-instance>.monaco-editor  .overflow-guard>.monaco-scrollable-element::before,` line. Result : no before created in monaco-scrollable-element class...
![image](https://user-images.githubusercontent.com/42498403/116322977-6af48780-a7bd-11eb-99ab-e7caf59219bc.png)

**Comment by Unthrottled** [comment] 2021-04-27 23:10
> Now checked in the devtool if css is working so I checked in the abyss of VSC CSS for finding the
[id="workbench.parts.editor"] .split-view-view .editor-container .editor-instance>.monaco-editor .overflow-guard>.monaco-scrollable-element::before, line. Result : no before created in monaco-scrollable-element class...

I am a bit confused what you where trying to do. What where you trying to verify the style was being applied? There are a ton of styles that support the glass pane wallpaper feature

See here https://github.com/doki-theme/doki-theme-vscode/blob/d03dc37aa08f884b0b3fc414a385e5efa8dd1631/src/StickerService.ts#L26

> Okay so just tried with the web link it's working (see on screen)

Cool! Not cool if you want to code offline though... I wonder why local content is not working. I think that is the issue that is preventing things from showing up

**Comment by Unthrottled** [comment] 2021-04-27 23:12
@master117 I've got a PR set up here https://github.com/doki-theme/doki-theme-vscode/pull/63 if you wanted to test it out (I've attached it in the description). I'll merge it tomorrow when I get the chance. Thanks!

**Comment by Clxmmm** [comment] 2021-04-27 23:18
> > Now checked in the devtool if css is working so I checked in the abyss of VSC CSS for finding the
> > [id="workbench.parts.editor"] .split-view-view .editor-container .editor-instance>.monaco-editor .overflow-guard>.monaco-scrollable-element::before, line. Result : no before created in monaco-scrollable-element class...
> 
> I am a bit confused what you where trying to do. What where you trying to verify the style was being applied? There are a ton of styles that support the glass pane wallpaper feature
> 
> See here
> 
> https://github.com/doki-theme/doki-theme-vscode/blob/d03dc37aa08f884b0b3fc414a385e5efa8dd1631/src/StickerService.ts#L26

Yeah yeah I was a bit motivated to find it and it didn't really worked...

> > Okay so just tried with the web link it's working (see on screen)
> 
> Cool! Not cool if you want to code offline though... I wonder why local content is not working. I think that is the issue that is preventing things from showing up

I've maybe an idea, for my main computer only, my VS Code can't update, maybe it's related. 
![image](https://user-images.githubusercontent.com/42498403/116323863-3255ad80-a7bf-11eb-9638-c136fd4d78e2.png)
If I don't find solution, I will use the direct link, I almost never code offline so it doesn't matter but it's sad to have to change it in the css..
Maybe PR will help i'll try tomorrow !
Thanks !

**Comment by Clxmmm** [comment] 2021-04-28 07:43
I think I've found the problem on my secondary computer !
It might be because in the path in css some char are not allowed or something like that
My appdata user is " Clem**'** " maybe the apostrophe is the big problem of everything ( and so i don't know if you can solve )

**Comment by Unthrottled** [comment] 2021-04-28 10:21
@Clxmmm Could you try URL encoding the string (eg: `Clem%27`)? If that works I can add logic in the plugin to generate url encode the local file path.

**Comment by Clxmmm** [comment] 2021-04-28 12:37
Yeah it's working ! It would be nice thanks !

**Closed** 2021-04-28 22:09 UTC

**Comment by Ghostel23** [comment] 2024-09-30 07:12
I'm having trouble getting the wallpaper to show, even though the theme shows, I'm not able to get it to work. The error pops up when I try to download but the error says, “The command could not be found” and I really don't know what to do. 
![image](https://github.com/user-attachments/assets/a49feaf0-8c00-459c-90e6-e1129a2276cf)

**Comment by Katyusha47** [comment] 2024-10-22 01:37
![Screenshot 2024-10-22 083642](https://github.com/user-attachments/assets/f0f6bd34-bcd7-4c4f-a454-fa1a7f0cdc53)

i have an issue. CSS doesnt appear
